module  Site

  CATEGORY = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'],  ['Home Deliver','HomeDeliver'] ]
  CATEGORY1 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'],  ['Home Deliver','HomeDeliver'] ]
  CATEGORY2 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'],  ['Home Deliver','HomeDeliver'] ]
  CATEGORY3 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'],  ['Home Deliver','HomeDeliver'] ]
  CATEGORY4 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'],  ['Home Deliver','HomeDeliver'] ]
  CATEGORY5 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon']  ]
  CATEGORY6 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'], ['Home Deliver','HomeDeliver'] ]
  CATEGORY7 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'], ['Home Deliver','HomeDeliver'] ]
  CATEGORY8 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'], ['Home Deliver','HomeDeliver'] ]
  CATEGORY9 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'],  ['Home Deliver','HomeDeliver'] ]
  CATEGORY10 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'],  ['Home Deliver','HomeDeliver'] ]
  CATEGORY11 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'],  ['Home Deliver','HomeDeliver'] ]
  CATEGORY12 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'], ['Home Deliver','HomeDeliver'] ]
  CATEGORY13 = [ ['Health & Beauty', 'Beauty'],  ['Banquet', 'Banquet'], ['Restaurant', 'Restaurant'], ['Home & Living', 'Living'], ['Hotel & Rooms', 'Room'], ['Pubs & Bar', 'PubsBar'], ['MixedBags', 'MixedBag'], ['Travels', 'Travel'] ,  ['Tuitioncoachs', 'Tuitioncoach'], ['Tourisms', 'Tourism'],['Softwares', 'Software'], ['Icon', 'Icon'], ['Home Deliver','HomeDeliver'] ]


  BANQUETS = [ [ 'Anniversary Parties', 'anniversary_parties' ], [ 'Birthdays Party', 'birthdays_party ' ], ['Bridal Showers', 'bridal_showers' ], ['Bar', 'bar' ],
             [ 'Corporate Functions', 'corporate_functions' ],[ 'cocktail Party ', 'cocktail_party ' ],[ 'Private Affairs', 'Private Affairs' ],[ 'Dinner Dances', 'dinner_dances' ],
             [ 'Engagement Parties', 'engagement_parties ' ], ['Family Reunions', 'family_reunions' ] , ['Cuisine', 'cuisine' ]            ]


  CATEGORIES = [ 'Health & Beauty', 'Banquet', 'Restaurant', 'Home Deliver' , 'Home & Living', 'Hotel & Rooms', 'Pubs & Bar', 'MixedBags' , 'Travels', 'Tuitioncoachs', 'Tourisms', 'Softwares', 'Icon' ]


end